### PR TITLE
Changed the logic for getting the minimum value

### PR DESCRIPTION
**Pull request by AndreyKovalevskiy**
Added two classes: Node and LinkedList. The logic for getting the minimum value on the stack has been changed so that the minimumValue() uses O (1) the amount of auxiliary memory.

### CODE REVIEW

**Review by dersim-davaod — COMMENTED** [review]
@AndreyKovalevskiy thanks for the PR!
Could you please add a description for your PR so I have an understanding why you have decided to change the logic?

**Comment by AndreyKovalevskiy** [comment]
@dersim-davaod added description for PR

**Comment by dersim-davaod** [comment]
> The logic for getting the minimum value on the stack has been changed so that the minimumValue() uses O (1) the amount of auxiliary memory.

@AndreyKovalevskiy, thank you for the description.

Could you please prove that?
Is that correct `minimumValue()` needs `O(1)` memory to do the job?

**Comment by AndreyKovalevskiy** [comment]
> > The logic for getting the minimum value on the stack has been changed so that the minimumValue() uses O (1) the amount of auxiliary memory.
> 
> @AndreyKovalevskiy, thank you for the description.
> 
> Could you please prove that?
> Is that correct `minimumValue()` needs `O(1)` memory to do the job?

@dersim-davaod Because the amount of memory allocated for the var list is constant and does not depend on the input data

**Comment by AndreyKovalevskiy** [comment]
PR is closed because getting the minimum element on the stack using a linked list (classes: Node and LinkedList) requires additional O(n) memory. This does not meet the original condition: O(1).

**Pull request closed without merging**
